-- D4: associate locally reserved tickets with the order id generated by ticket-service.
-- Existing rows intentionally remain NULL; every D4 purchase writes a non-null value.
USE 12306_ticket;

ALTER TABLE `t_ticket`
    ADD COLUMN `order_sn` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '关联订单号' AFTER `id`,
    ADD KEY `idx_order_sn` (`order_sn`) USING BTREE;
